// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_F0NG8hrGbtDXiQjJHa4ItrXJahvGHw',
    appId: '1:694884663195:android:392a60b7e4f8d0a520eb3e',
    messagingSenderId: '694884663195',
    projectId: 'akarena',
    databaseURL: 'https://akarena-default-rtdb.firebaseio.com',
    storageBucket: 'akarena.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdA-3of_aLRweqaaGmkyEBJJrKCTtKRmU',
    appId: '1:694884663195:ios:f1418b23a812084020eb3e',
    messagingSenderId: '694884663195',
    projectId: 'akarena',
    databaseURL: 'https://akarena-default-rtdb.firebaseio.com',
    storageBucket: 'akarena.firebasestorage.app',
    iosClientId: '694884663195-cp58n12k4crc7cepbhnltj83ogprb7u9.apps.googleusercontent.com',
    iosBundleId: 'com.agharinaa.com',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uek2f4HGDee6KXYrtkaWetsVJyyBn4g',
    appId: '1:694884663195:web:5942545931505bd720eb3e',
    messagingSenderId: '694884663195',
    projectId: 'akarena',
    authDomain: 'akarena.firebaseapp.com',
    databaseURL: 'https://akarena-default-rtdb.firebaseio.com',
    storageBucket: 'akarena.firebasestorage.app',
    measurementId: 'G-YMETZTWQMB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdA-3of_aLRweqaaGmkyEBJJrKCTtKRmU',
    appId: '1:694884663195:ios:f1418b23a812084020eb3e',
    messagingSenderId: '694884663195',
    projectId: 'akarena',
    databaseURL: 'https://akarena-default-rtdb.firebaseio.com',
    storageBucket: 'akarena.firebasestorage.app',
    iosClientId: '694884663195-cp58n12k4crc7cepbhnltj83ogprb7u9.apps.googleusercontent.com',
    iosBundleId: 'com.agharinaa.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2uek2f4HGDee6KXYrtkaWetsVJyyBn4g',
    appId: '1:694884663195:web:1f7cae34660a1b7420eb3e',
    messagingSenderId: '694884663195',
    projectId: 'akarena',
    authDomain: 'akarena.firebaseapp.com',
    databaseURL: 'https://akarena-default-rtdb.firebaseio.com',
    storageBucket: 'akarena.firebasestorage.app',
    measurementId: 'G-J6YMHPNRVN',
  );
}
